# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      
      db:
        image: mysql:8.0.23
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --name db --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: |
        docker cp $(pwd)/APIProjectMoviesWebII/Scripts/createDB.sql db:/script.sql
        docker exec db /bin/bash -c 'mysql -uroot -proot < script.sql'
        docker cp $(pwd)/APIProjectMoviesWebII/Scripts/populate.sql db:/script2.sql
        docker exec db /bin/bash -c 'mysql -uroot -proot < script2.sql'
        mvn package --file APIProjectMoviesWebII/pom.xml
